[platformio]
    default_envs = flightComputer
    src_dir = .

[common]
    build_flags =
        -std=gnu11
        -g3
        -O0
        -Os
        -ffunction-sections
        -fdata-sections
        -Wall
        -fstack-usage
        --specs=nano.specs

[env:flightComputer]
    platform = ststm32
    framework = stm32cube
    board = flightComputer

    ; PlatformIO uses this directory to look for the libs listed below
    lib_extra_dirs =
        fc/lib

    lib_deps = 
        FatFS = file://fc/lib/FatFS
        FreeRTOS = file://fc/lib/FreeRTOS
        ; ST_USB
        mbed-jsoh91/Eigen

    build_src_filter = 
        -<*>
        +<fc/MRT/**>

        +<fc/Src> ; Compile all HAL Drivers

    lib_ldf_mode = deep+

    extra_scripts = pre:fc/force_fpu.py

    ; Build options
    build_flags =
        ${common.build_flags}
        -I fc/Inc

        -I fc/MRT       
        -I Drivers

        ; Includes for FreeRTOS headers
        -I fc/lib/FreeRTOS/Source/include
        -I fc/lib/FreeRTOS/Source/CMSIS_RTOS_V2
        -I fc/lib/FreeRTOS/Source/portable/GCC/ARM_CM4F

        ; Includes for FatFS headers
        -I fc/FATFS/App
        -I fc/FATFS/Target

        ; FPU Config
        -mfloat-abi=hard
        -mfpu=fpv4-sp-d16
        -DSTM32F4xx

[env:prop_top]
    platform = ststm32
    framework = stm32cube
    board = propulsionController

    lib_extra_dirs =
        prop_top/MRT

    lib_ldf_mode = deep+

    build_src_filter = 
        -<*>
        +<prop_top/MRT/**>

        +<prop_top/Src> ; Compile all HAL Drivers

    ; Build options
    build_flags =
        ${common.build_flags}
        -I prop_top/Inc
        -I prop_top/MRT

        -I Drivers

    ; Serial Monitor options
    monitor_speed = 115200

[env:prop_bottom]
    platform = ststm32
    framework = stm32cube
    board = propulsionController

    lib_extra_dirs =
        prop_bottom/MRT

    lib_ldf_mode = deep+

    build_src_filter = 
        -<*>
        +<prop_bottom/MRT/**>

        +<prop_bottom/Src> ; Compile all HAL Drivers

    ; Build options
    build_flags =
        ${common.build_flags}
        -I prop_bottom/Inc
        -I prop_bottom/MRT

        -I Drivers

    ; Serial Monitor options
    monitor_speed = 115200